export interface LearnWord {
  id: number;
  romanUrdu: string;
  urduScript: string;
  english: string;
  exampleSentence: string;
}

export interface LearnDay {
  day: number;
  title: string;
  phase: string;
  words: LearnWord[];
}

export interface LearnPhase {
  phase: number;
  title: string;
  dayRange: string;
  days: LearnDay[];
}

export const learn40Data: LearnPhase[] = [
  {
    phase: 1,
    title: "Foundations",
    dayRange: "1-10",
    days: [
      {
        day: 1,
        title: "Greetings",
        phase: "Foundations",
        words: [
          {
            id: 1,
            romanUrdu: "Assalam-o-Alaikum",
            urduScript: "السلام علیکم",
            english: "Hello (peace be upon you)",
            exampleSentence: "Assalam-o-Alaikum, kaise hain aap?",
          },
          {
            id: 2,
            romanUrdu: "Walaikum Assalam",
            urduScript: "وعلیکم السلام",
            english: "Reply to hello",
            exampleSentence: "Walaikum Assalam, main theek hoon.",
          },
          {
            id: 3,
            romanUrdu: "Kaise hain?",
            urduScript: "کیسے ہیں؟",
            english: "How are you? (formal)",
            exampleSentence: "Aap kaise hain?",
          },
          {
            id: 4,
            romanUrdu: "Theek hoon",
            urduScript: "ٹھیک ہوں",
            english: "I am fine",
            exampleSentence: "Main theek hoon, shukriya.",
          },
          {
            id: 5,
            romanUrdu: "Shukriya",
            urduScript: "شکریہ",
            english: "Thank you",
            exampleSentence: "Shukriya, aap bohat acche hain.",
          },
        ],
      },
      {
        day: 2,
        title: 'Pronouns & "To Be"',
        phase: "Foundations",
        words: [
          {
            id: 6,
            romanUrdu: "Main",
            urduScript: "میں",
            english: "I",
            exampleSentence: "Main theek hoon.",
          },
          {
            id: 7,
            romanUrdu: "Tum",
            urduScript: "تم",
            english: "You (informal)",
            exampleSentence: "Tum kaise ho?",
          },
          {
            id: 8,
            romanUrdu: "Aap",
            urduScript: "آپ",
            english: "You (formal/respectful)",
            exampleSentence: "Aap kaise hain?",
          },
          {
            id: 9,
            romanUrdu: "Woh",
            urduScript: "وہ",
            english: "He/She/It",
            exampleSentence: "Woh acha hai.",
          },
          {
            id: 10,
            romanUrdu: "Hum",
            urduScript: "ہم",
            english: "We",
            exampleSentence: "Hum theek hain.",
          },
        ],
      },
      {
        day: 3,
        title: "Numbers 1–10",
        phase: "Foundations",
        words: [
          {
            id: 11,
            romanUrdu: "Aik",
            urduScript: "ایک",
            english: "One",
            exampleSentence: "",
          },
          {
            id: 12,
            romanUrdu: "Do",
            urduScript: "دو",
            english: "Two",
            exampleSentence: "",
          },
          {
            id: 13,
            romanUrdu: "Teen",
            urduScript: "تین",
            english: "Three",
            exampleSentence: "",
          },
          {
            id: 14,
            romanUrdu: "Chaar",
            urduScript: "چار",
            english: "Four",
            exampleSentence: "",
          },
          {
            id: 15,
            romanUrdu: "Paanch",
            urduScript: "پانچ",
            english: "Five",
            exampleSentence: "",
          },
          {
            id: 16,
            romanUrdu: "Chhay",
            urduScript: "چھ",
            english: "Six",
            exampleSentence: "",
          },
          {
            id: 17,
            romanUrdu: "Saat",
            urduScript: "سات",
            english: "Seven",
            exampleSentence: "",
          },
          {
            id: 18,
            romanUrdu: "Aath",
            urduScript: "آٹھ",
            english: "Eight",
            exampleSentence: "",
          },
          {
            id: 19,
            romanUrdu: "Nau",
            urduScript: "نو",
            english: "Nine",
            exampleSentence: "",
          },
          {
            id: 20,
            romanUrdu: "Dus",
            urduScript: "دس",
            english: "Ten",
            exampleSentence: "",
          },
        ],
      },
      {
        day: 4,
        title: "Politeness Words",
        phase: "Foundations",
        words: [
          {
            id: 21,
            romanUrdu: "Haan",
            urduScript: "ہاں",
            english: "Yes",
            exampleSentence: "Haan, main theek hoon.",
          },
          {
            id: 22,
            romanUrdu: "Nahi",
            urduScript: "نہیں",
            english: "No",
            exampleSentence: "Nahi, main theek nahi hoon.",
          },
          {
            id: 23,
            romanUrdu: "Meherbani",
            urduScript: "مہربانی",
            english: "Please",
            exampleSentence: "Meherbani, ek minute.",
          },
          {
            id: 24,
            romanUrdu: "Maaf kijiye",
            urduScript: "معاف کیجیے",
            english: "Sorry/Excuse me",
            exampleSentence: "Maaf kijiye, main late hoon.",
          },
          {
            id: 25,
            romanUrdu: "Koi baat nahi",
            urduScript: "کوئی بات نہیں",
            english: "No problem",
            exampleSentence: "Koi baat nahi, sab theek hai.",
          },
        ],
      },
      {
        day: 6,
        title: "Question Words",
        phase: "Foundations",
        words: [
          {
            id: 26,
            romanUrdu: "Kya",
            urduScript: "کیا",
            english: "What",
            exampleSentence: "Yeh kya hai?",
          },
          {
            id: 27,
            romanUrdu: "Kaun",
            urduScript: "کون",
            english: "Who",
            exampleSentence: "Woh kaun hai?",
          },
          {
            id: 28,
            romanUrdu: "Kahan",
            urduScript: "کہاں",
            english: "Where",
            exampleSentence: "Aap kahan hain?",
          },
          {
            id: 29,
            romanUrdu: "Kab",
            urduScript: "کب",
            english: "When",
            exampleSentence: "Kab aayenge aap?",
          },
          {
            id: 30,
            romanUrdu: "Kyun",
            urduScript: "کیوں",
            english: "Why",
            exampleSentence: "Kyun nahi?",
          },
        ],
      },
      {
        day: 7,
        title: "Common Nouns",
        phase: "Foundations",
        words: [
          {
            id: 31,
            romanUrdu: "Ghar",
            urduScript: "گھر",
            english: "House",
            exampleSentence: "Yeh mera ghar hai.",
          },
          {
            id: 32,
            romanUrdu: "Pani",
            urduScript: "پانی",
            english: "Water",
            exampleSentence: "Mujhe pani chahiye. (preview of Day 21 pattern)",
          },
          {
            id: 33,
            romanUrdu: "Khana",
            urduScript: "کھانا",
            english: "Food",
            exampleSentence: "Khana acha hai.",
          },
          {
            id: 34,
            romanUrdu: "Dost",
            urduScript: "دوست",
            english: "Friend",
            exampleSentence: "Woh mera dost hai.",
          },
          {
            id: 35,
            romanUrdu: "Kitaab",
            urduScript: "کتاب",
            english: "Book",
            exampleSentence: "Yeh kitaab acchi hai.",
          },
        ],
      },
      {
        day: 8,
        title: "Adjectives",
        phase: "Foundations",
        words: [
          {
            id: 36,
            romanUrdu: "Acha",
            urduScript: "اچھا",
            english: "Good",
            exampleSentence: "Yeh acha hai.",
          },
          {
            id: 37,
            romanUrdu: "Bura",
            urduScript: "برا",
            english: "Bad",
            exampleSentence: "Yeh bura hai.",
          },
          {
            id: 38,
            romanUrdu: "Bara",
            urduScript: "بڑا",
            english: "Big",
            exampleSentence: "Ghar bara hai.",
          },
          {
            id: 39,
            romanUrdu: "Chota",
            urduScript: "چھوٹا",
            english: "Small",
            exampleSentence: "Kitaab chota hai.",
          },
          {
            id: 40,
            romanUrdu: "Naya",
            urduScript: "نیا",
            english: "New",
            exampleSentence: "Yeh naya dost hai.",
          },
        ],
      },
      {
        day: 9,
        title: "Numbers 11–20 + Colors",
        phase: "Foundations",
        words: [
          {
            id: 41,
            romanUrdu: "Gyarah",
            urduScript: "گیارہ",
            english: "11",
            exampleSentence: "",
          },
          {
            id: 42,
            romanUrdu: "Barah",
            urduScript: "بارہ",
            english: "12",
            exampleSentence: "",
          },
          {
            id: 43,
            romanUrdu: "Pandrah",
            urduScript: "پندرہ",
            english: "15",
            exampleSentence: "",
          },
          {
            id: 44,
            romanUrdu: "Bees",
            urduScript: "بیس",
            english: "20",
            exampleSentence: "",
          },
          {
            id: 45,
            romanUrdu: "Laal",
            urduScript: "لال",
            english: "Red",
            exampleSentence: "",
          },
          {
            id: 46,
            romanUrdu: "Neela",
            urduScript: "نیلا",
            english: "Blue",
            exampleSentence: "",
          },
          {
            id: 47,
            romanUrdu: "Sabz",
            urduScript: "سبز",
            english: "Green",
            exampleSentence: "",
          },
          {
            id: 48,
            romanUrdu: "Kaala",
            urduScript: "کالا",
            english: "Black",
            exampleSentence: "",
          },
          {
            id: 49,
            romanUrdu: "Safed",
            urduScript: "سفید",
            english: "White",
            exampleSentence: "",
          },
        ],
      },
    ],
  },
  {
    phase: 2,
    title: "Survival",
    dayRange: "11-20",
    days: [
      {
        day: 11,
        title: "Family Words",
        phase: "Survival",
        words: [
          {
            id: 50,
            romanUrdu: "Ammi",
            urduScript: "امی",
            english: "Mother",
            exampleSentence: "Yeh meri Ammi hai.",
          },
          {
            id: 51,
            romanUrdu: "Abbu",
            urduScript: "ابو",
            english: "Father",
            exampleSentence: "Yeh mera Abbu hai.",
          },
          {
            id: 52,
            romanUrdu: "Bhai",
            urduScript: "بھائی",
            english: "Brother",
            exampleSentence: "Mera bhai bara hai.",
          },
          {
            id: 53,
            romanUrdu: "Behan",
            urduScript: "بہن",
            english: "Sister",
            exampleSentence: "Meri behan chota hai.",
          },
          {
            id: 54,
            romanUrdu: "Beta/Beti",
            urduScript: "بیٹا/بیٹی",
            english: "Son/Daughter",
            exampleSentence: "Woh unka beta hai.",
          },
        ],
      },
      {
        day: 12,
        title: 'Possession ("Mere paas")',
        phase: "Survival",
        words: [
          {
            id: 55,
            romanUrdu: "Tera/Teri",
            urduScript: "تیرا/تیری",
            english: "Your (informal)",
            exampleSentence: "Yeh tera ghar hai.",
          },
          {
            id: 56,
            romanUrdu: "Uska/Uski",
            urduScript: "اسکا/اسکی",
            english: "His/Her",
            exampleSentence: "Yeh uska dost hai.",
          },
          {
            id: 57,
            romanUrdu: "Mere paas",
            urduScript: "میرے پاس",
            english: "I have (lit. near me)",
            exampleSentence: "Mere paas ek kitaab hai.",
          },
          {
            id: 58,
            romanUrdu: "Hamara/Hamari",
            urduScript: "ہمارا/ہماری",
            english: "Our",
            exampleSentence: "Yeh hamara ghar hai.",
          },
          {
            id: 59,
            romanUrdu: "Unka/Unki",
            urduScript: "انکا/انکی",
            english: "Their",
            exampleSentence: "Yeh unka beta hai.",
          },
        ],
      },
      {
        day: 13,
        title: "House & Rooms",
        phase: "Survival",
        words: [
          {
            id: 60,
            romanUrdu: "Kamra",
            urduScript: "کمرہ",
            english: "Room",
            exampleSentence: "Yeh mera kamra hai.",
          },
          {
            id: 61,
            romanUrdu: "Rasoi",
            urduScript: "رسائی",
            english: "Kitchen",
            exampleSentence: "Ammi rasoi mein hain.",
          },
          {
            id: 62,
            romanUrdu: "Bathroom",
            urduScript: "بیت الخلا",
            english: "Bathroom",
            exampleSentence: "Bathroom kahan hai?",
          },
          {
            id: 63,
            romanUrdu: "Chhat",
            urduScript: "چھت",
            english: "Roof/Terrace",
            exampleSentence: "Hum chhat par baithte hain.",
          },
          {
            id: 64,
            romanUrdu: "Darwaza",
            urduScript: "دروازہ",
            english: "Door",
            exampleSentence: "Darwaza band karo.",
          },
        ],
      },
      {
        day: 14,
        title: "Days of the Week",
        phase: "Survival",
        words: [
          {
            id: 65,
            romanUrdu: "Peer",
            urduScript: "پیر",
            english: "Monday",
            exampleSentence: "",
          },
          {
            id: 66,
            romanUrdu: "Mangal",
            urduScript: "منگل",
            english: "Tuesday",
            exampleSentence: "",
          },
          {
            id: 67,
            romanUrdu: "Budh",
            urduScript: "بدھ",
            english: "Wednesday",
            exampleSentence: "",
          },
          {
            id: 68,
            romanUrdu: "Jumeraat",
            urduScript: "جمعرات",
            english: "Thursday",
            exampleSentence: "",
          },
          {
            id: 69,
            romanUrdu: "Jumma",
            urduScript: "جمعہ",
            english: "Friday",
            exampleSentence: "",
          },
          {
            id: 70,
            romanUrdu: "Hafta",
            urduScript: "ہفتہ",
            english: "Saturday",
            exampleSentence: "",
          },
          {
            id: 71,
            romanUrdu: "Itwaar",
            urduScript: "اتوار",
            english: "Sunday",
            exampleSentence: "",
          },
        ],
      },
      {
        day: 16,
        title: "Daily Routine Verbs (Present Tense)",
        phase: "Survival",
        words: [
          {
            id: 72,
            romanUrdu: "Uthna → Uthta/Uthti hoon",
            urduScript: "اٹھنا → اٹھتا/اٹھتی ہوں",
            english: "To wake up → I wake up",
            exampleSentence: "Main subah uthta hoon. (m) / uthti hoon (f)",
          },
          {
            id: 73,
            romanUrdu: "Khana → Khata/Khati hoon",
            urduScript: "کھانا → کھاتا/کھاتی ہوں",
            english: "To eat → I eat",
            exampleSentence: "Main khana khata hoon.",
          },
          {
            id: 74,
            romanUrdu: "Sona → Sota/Soti hoon",
            urduScript: "سونا → سوتا/سوتی ہوں",
            english: "To sleep → I sleep",
            exampleSentence: "Main raat ko sota hoon.",
          },
          {
            id: 75,
            romanUrdu: "Jaana → Jata/Jati hoon",
            urduScript: "جانا → جاتا/جاتی ہوں",
            english: "To go → I go",
            exampleSentence: "Main school jata hoon.",
          },
          {
            id: 76,
            romanUrdu: "Karna → Karta/Karti hoon",
            urduScript: "کرنا → کرتا/کرتی ہوں",
            english: "To do → I do",
            exampleSentence: "Main kaam karta hoon.",
          },
        ],
      },
      {
        day: 17,
        title: "Time Vocabulary",
        phase: "Survival",
        words: [
          {
            id: 77,
            romanUrdu: "Waqt",
            urduScript: "وقت",
            english: "Time",
            exampleSentence: "Kya waqt hua hai?",
          },
          {
            id: 78,
            romanUrdu: "Ghanta",
            urduScript: "گھنٹہ",
            english: "Hour",
            exampleSentence: "Ek ghanta baad.",
          },
          {
            id: 79,
            romanUrdu: "Minute",
            urduScript: "منٹ",
            english: "Minute",
            exampleSentence: "Do minute ruko.",
          },
          {
            id: 80,
            romanUrdu: "Subah",
            urduScript: "صبح",
            english: "Morning",
            exampleSentence: "Subah bakhair.",
          },
          {
            id: 81,
            romanUrdu: "Shaam",
            urduScript: "شام",
            english: "Evening",
            exampleSentence: "Shaam ko milte hain.",
          },
        ],
      },
      {
        day: 18,
        title: "More Routine Verbs",
        phase: "Survival",
        words: [
          {
            id: 82,
            romanUrdu: "Parhna → Parhta/Parhti hoon",
            urduScript: "پڑھنا → پڑھتا/پڑھتی ہوں",
            english: "To study/read",
            exampleSentence: "Main kitaab parhta hoon.",
          },
          {
            id: 83,
            romanUrdu: "Likhna → Likhta/Likhti hoon",
            urduScript: "لکھنا → لکھتا/لکھتی ہوں",
            english: "To write",
            exampleSentence: "Main letter likhta hoon.",
          },
          {
            id: 84,
            romanUrdu: "Khelna → Khelta/Khelti hoon",
            urduScript: "کھیلنا → کھیلتا/کھیلتی ہوں",
            english: "To play",
            exampleSentence: "Hum khelte hain.",
          },
          {
            id: 85,
            romanUrdu: "Dekhna → Dekhta/Dekhti hoon",
            urduScript: "دیکھنا → دیکھتا/دیکھتی ہوں",
            english: "To watch/see",
            exampleSentence: "Main TV dekhta hoon.",
          },
          {
            id: 86,
            romanUrdu: "Sunna → Sunta/Sunti hoon",
            urduScript: "سننا → سنتا/سنتی ہوں",
            english: "To listen",
            exampleSentence: "Main gaana sunta hoon.",
          },
        ],
      },
      {
        day: 19,
        title: "Sequencing Routine",
        phase: "Survival",
        words: [
          {
            id: 87,
            romanUrdu: "Phir",
            urduScript: "پھر",
            english: "Then",
            exampleSentence: "Main uthta hoon, phir khana khata hoon.",
          },
          {
            id: 88,
            romanUrdu: "Uske baad",
            urduScript: "اس کے بعد",
            english: "After that",
            exampleSentence: "Uske baad main school jata hoon.",
          },
          {
            id: 89,
            romanUrdu: "Sab se pehle",
            urduScript: "سب سے پہلے",
            english: "First of all",
            exampleSentence: "Sab se pehle main uthta hoon.",
          },
          {
            id: 90,
            romanUrdu: "Akhir mein",
            urduScript: "آخر میں",
            english: "Finally",
            exampleSentence: "Akhir mein main sota hoon.",
          },
        ],
      },
    ],
  },
  {
    phase: 3,
    title: "Social",
    dayRange: "21-30",
    days: [
      {
        day: 21,
        title: "Food & Drink",
        phase: "Social",
        words: [
          {
            id: 91,
            romanUrdu: "Roti",
            urduScript: "روٹی",
            english: "Bread",
            exampleSentence: "Mujhe roti chahiye.",
          },
          {
            id: 92,
            romanUrdu: "Chawal",
            urduScript: "چاول",
            english: "Rice",
            exampleSentence: "Chawal acha hai.",
          },
          {
            id: 93,
            romanUrdu: "Chai",
            urduScript: "چائے",
            english: "Tea",
            exampleSentence: "Mujhe chai chahiye.",
          },
          {
            id: 94,
            romanUrdu: "Doodh",
            urduScript: "دودھ",
            english: "Milk",
            exampleSentence: "Bachon ko doodh chahiye.",
          },
          {
            id: 95,
            romanUrdu: "Sabzi",
            urduScript: "سبزی",
            english: "Vegetable",
            exampleSentence: "Sabzi taza hai.",
          },
        ],
      },
      {
        day: 22,
        title: "Market & Shopping",
        phase: "Social",
        words: [
          {
            id: 96,
            romanUrdu: "Dukaan",
            urduScript: "دکان",
            english: "Shop",
            exampleSentence: "Yeh dukaan bari hai.",
          },
          {
            id: 97,
            romanUrdu: "Paisa",
            urduScript: "پیسہ",
            english: "Money",
            exampleSentence: "Mere paas paisa nahi hai.",
          },
          {
            id: 98,
            romanUrdu: "Sasta",
            urduScript: "سستا",
            english: "Cheap",
            exampleSentence: "Yeh sasta hai.",
          },
          {
            id: 99,
            romanUrdu: "Mehnga",
            urduScript: "مہنگا",
            english: "Expensive",
            exampleSentence: "Yeh bohat mehnga hai.",
          },
          {
            id: 100,
            romanUrdu: "Bill",
            urduScript: "بل",
            english: "Bill",
            exampleSentence: "Bill kitna hai?",
          },
        ],
      },
      {
        day: 23,
        title: "Numbers 20–100 (by tens)",
        phase: "Social",
        words: [
          {
            id: 101,
            romanUrdu: "Bees",
            urduScript: "بیس",
            english: "20",
            exampleSentence: "",
          },
          {
            id: 102,
            romanUrdu: "Tees",
            urduScript: "تیس",
            english: "30",
            exampleSentence: "",
          },
          {
            id: 103,
            romanUrdu: "Chalees",
            urduScript: "چالیس",
            english: "40",
            exampleSentence: "",
          },
          {
            id: 104,
            romanUrdu: "Pachas",
            urduScript: "پچاس",
            english: "50",
            exampleSentence: "",
          },
          {
            id: 105,
            romanUrdu: "Saath",
            urduScript: "ساٹھ",
            english: "60",
            exampleSentence: "",
          },
          {
            id: 106,
            romanUrdu: "Sattar",
            urduScript: "ستّور",
            english: "70",
            exampleSentence: "",
          },
          {
            id: 107,
            romanUrdu: "Assi",
            urduScript: "اسی",
            english: "80",
            exampleSentence: "",
          },
          {
            id: 108,
            romanUrdu: "Nabbay",
            urduScript: "نوّے",
            english: "90",
            exampleSentence: "",
          },
          {
            id: 109,
            romanUrdu: "Sau",
            urduScript: "سو",
            english: "100",
            exampleSentence: "",
          },
        ],
      },
      {
        day: 24,
        title: "Restaurant Phrases",
        phase: "Social",
        words: [
          {
            id: 110,
            romanUrdu: "Menu",
            urduScript: "مینو",
            english: "Menu",
            exampleSentence: "Menu dikhayen.",
          },
          {
            id: 111,
            romanUrdu: "Order",
            urduScript: "آرڈر",
            english: "Order",
            exampleSentence: "Main order karna chahta hoon.",
          },
          {
            id: 112,
            romanUrdu: "Pasand",
            urduScript: "پسند",
            english: "Like/preference",
            exampleSentence: "Mujhe yeh pasand hai.",
          },
          {
            id: 113,
            romanUrdu: "Naapasand",
            urduScript: "ناپسند",
            english: "Dislike",
            exampleSentence: "Mujhe yeh naapasand hai.",
          },
          {
            id: 114,
            romanUrdu: "Bhook",
            urduScript: "بھوک",
            english: "Hunger",
            exampleSentence: "Mujhe bhook hai.",
          },
        ],
      },
      {
        day: 26,
        title: "Directions",
        phase: "Social",
        words: [
          {
            id: 115,
            romanUrdu: "Seedha",
            urduScript: "سیدھا",
            english: "Straight",
            exampleSentence: "Seedha jayen.",
          },
          {
            id: 116,
            romanUrdu: "Bayen",
            urduScript: "بائیں",
            english: "Left",
            exampleSentence: "Bayen mudein.",
          },
          {
            id: 117,
            romanUrdu: "Dayen",
            urduScript: "دائیں",
            english: "Right",
            exampleSentence: "Dayen mudein.",
          },
          {
            id: 118,
            romanUrdu: "Pass",
            urduScript: "پاس",
            english: "Near",
            exampleSentence: "Yeh school ke pass hai.",
          },
          {
            id: 119,
            romanUrdu: "Door",
            urduScript: "دور",
            english: "Far",
            exampleSentence: "Yeh bohat door hai.",
          },
        ],
      },
      {
        day: 27,
        title: "Places",
        phase: "Social",
        words: [
          {
            id: 120,
            romanUrdu: "Bazaar",
            urduScript: "بازار",
            english: "Market",
            exampleSentence: "Bazaar kahan hai?",
          },
          {
            id: 121,
            romanUrdu: "Station",
            urduScript: "اسٹیشن",
            english: "Station",
            exampleSentence: "Station door hai.",
          },
          {
            id: 122,
            romanUrdu: "Hospital",
            urduScript: "ہسپتال",
            english: "Hospital",
            exampleSentence: "Hospital pass hai.",
          },
          {
            id: 123,
            romanUrdu: "Masjid",
            urduScript: "مسجد",
            english: "Mosque",
            exampleSentence: "Masjid seedha hai.",
          },
          {
            id: 124,
            romanUrdu: "School",
            urduScript: "اسکول",
            english: "School",
            exampleSentence: "School kahan hai?",
          },
        ],
      },
      {
        day: 28,
        title: "Past Tense Basics",
        phase: "Social",
        words: [
          {
            id: 125,
            romanUrdu: "Tha (m) / Thi (f)",
            urduScript: "تھا (مرد) / تھی (عورت)",
            english: "Was",
            exampleSentence: "Main school mein tha.",
          },
          {
            id: 126,
            romanUrdu: "Thay",
            urduScript: "تھے",
            english: "Were (plural)",
            exampleSentence: "Hum bazaar mein thay.",
          },
          {
            id: 127,
            romanUrdu: "Gaya (m) / Gayi (f)",
            urduScript: "گیا (مرد) / گئی (عورت)",
            english: "Went",
            exampleSentence: "Main school gaya.",
          },
          {
            id: 128,
            romanUrdu: "Aaya (m) / Aayi (f)",
            urduScript: "آیا (مرد) / آئی (عورت)",
            english: "Came",
            exampleSentence: "Woh ghar aaya.",
          },
        ],
      },
      {
        day: 29,
        title: "Needs & Emergencies",
        phase: "Social",
        words: [
          {
            id: 129,
            romanUrdu: "Madad",
            urduScript: "مدد",
            english: "Help",
            exampleSentence: "Mujhe madad chahiye.",
          },
          {
            id: 130,
            romanUrdu: "Bimaar",
            urduScript: "بیمار",
            english: "Sick",
            exampleSentence: "Main bimaar hoon.",
          },
          {
            id: 131,
            romanUrdu: "Dard",
            urduScript: "درد",
            english: "Pain",
            exampleSentence: "Mujhe sar mein dard hai.",
          },
          {
            id: 132,
            romanUrdu: "Doctor",
            urduScript: "ڈاکٹر",
            english: "Doctor",
            exampleSentence: "Mujhe doctor chahiye.",
          },
          {
            id: 133,
            romanUrdu: "Dawai",
            urduScript: "دوائی",
            english: "Medicine",
            exampleSentence: "Mujhe dawai chahiye.",
          },
        ],
      },
    ],
  },
  {
    phase: 4,
    title: "Advanced",
    dayRange: "31-40",
    days: [
      {
        day: 31,
        title: "Opinions",
        phase: "Advanced",
        words: [
          {
            id: 134,
            romanUrdu: "Pasand hai",
            urduScript: "پسند ہے",
            english: "Like (reinforced from Day 24)",
            exampleSentence: "Mujhe yeh gaana pasand hai.",
          },
          {
            id: 135,
            romanUrdu: "Acha lagta hai",
            urduScript: "اچھا لگتا ہے",
            english: "Feels/seems good",
            exampleSentence: "Mujhe yahan acha lagta hai.",
          },
          {
            id: 136,
            romanUrdu: "Mushkil",
            urduScript: "مشکل",
            english: "Difficult",
            exampleSentence: "Urdu seekhna mushkil hai.",
          },
          {
            id: 137,
            romanUrdu: "Aasan",
            urduScript: "آسان",
            english: "Easy",
            exampleSentence: "Yeh sawaal aasan hai.",
          },
          {
            id: 138,
            romanUrdu: "Lagta hai",
            urduScript: "لگتا ہے",
            english: "Seems/feels",
            exampleSentence: "Mujhe lagta hai woh theek hai.",
          },
        ],
      },
      {
        day: 32,
        title: "Future Tense",
        phase: "Advanced",
        words: [
          {
            id: 139,
            romanUrdu: "Ga (m)",
            urduScript: "گا (مرد)",
            english: "Will (male subject)",
            exampleSentence: "Main jaaonga.",
          },
          {
            id: 140,
            romanUrdu: "Gi (f)",
            urduScript: "گی (عورت)",
            english: "Will (female subject)",
            exampleSentence: "Main jaaongi.",
          },
          {
            id: 141,
            romanUrdu: "Ge",
            urduScript: "گے",
            english: "Will (plural)",
            exampleSentence: "Hum jayenge.",
          },
          {
            id: 142,
            romanUrdu: "Karoonga/Karoongi",
            urduScript: "کروں گا/کروں گی",
            english: "Will do",
            exampleSentence: "Main kaam karoonga.",
          },
        ],
      },
      {
        day: 33,
        title: "Plans & Weekend Talk",
        phase: "Advanced",
        words: [
          {
            id: 143,
            romanUrdu: "Kal",
            urduScript: "کل",
            english: "Tomorrow/Yesterday (context-dependent)",
            exampleSentence: "Kal milte hain.",
          },
          {
            id: 144,
            romanUrdu: "Agle hafte",
            urduScript: "اگلے ہفتے",
            english: "Next week",
            exampleSentence: "Agle hafte party hai.",
          },
          {
            id: 145,
            romanUrdu: "Plan",
            urduScript: "پلان",
            english: "Plan",
            exampleSentence: "Mera plan hai ghar jana.",
          },
          {
            id: 146,
            romanUrdu: "Mulaqat",
            urduScript: "ملاقات",
            english: "Meeting",
            exampleSentence: "Mulaqat kab hai?",
          },
        ],
      },
      {
        day: 34,
        title: "Connectors",
        phase: "Advanced",
        words: [
          {
            id: 147,
            romanUrdu: "Aur",
            urduScript: "اور",
            english: "And",
            exampleSentence: "Main aur mera dost.",
          },
          {
            id: 148,
            romanUrdu: "Lekin",
            urduScript: "لیکن",
            english: "But",
            exampleSentence: "Acha hai, lekin mehnga hai.",
          },
          {
            id: 149,
            romanUrdu: "Kyunki",
            urduScript: "کیونکہ",
            english: "Because",
            exampleSentence: "Main khush hoon kyunki aaj Jumma hai.",
          },
          {
            id: 150,
            romanUrdu: "Isliye",
            urduScript: "اس لیے",
            english: "So/therefore",
            exampleSentence: "Mujhe bhook hai, isliye main khana khaonga.",
          },
        ],
      },
      {
        day: 36,
        title: "Feelings",
        phase: "Advanced",
        words: [
          {
            id: 151,
            romanUrdu: "Khush",
            urduScript: "خوش",
            english: "Happy",
            exampleSentence: "Main khush hoon.",
          },
          {
            id: 152,
            romanUrdu: "Udaas",
            urduScript: "اداس",
            english: "Sad",
            exampleSentence: "Woh udaas hai.",
          },
          {
            id: 153,
            romanUrdu: "Pareshan",
            urduScript: "پریشان",
            english: "Worried/Troubled",
            exampleSentence: "Main pareshan hoon.",
          },
          {
            id: 154,
            romanUrdu: "Hairaan",
            urduScript: "حیران",
            english: "Surprised",
            exampleSentence: "Main hairaan hoon!",
          },
          {
            id: 155,
            romanUrdu: "Thaka",
            urduScript: "تھکا",
            english: "Tired",
            exampleSentence: "Main thaka hoon.",
          },
        ],
      },
      {
        day: 37,
        title: "Weather & Small Talk",
        phase: "Advanced",
        words: [
          {
            id: 156,
            romanUrdu: "Garmi",
            urduScript: "گرمی",
            english: "Heat",
            exampleSentence: "Aaj bohat garmi hai.",
          },
          {
            id: 157,
            romanUrdu: "Sardi",
            urduScript: "سردی",
            english: "Cold",
            exampleSentence: "Sardi shuru ho gayi hai.",
          },
          {
            id: 158,
            romanUrdu: "Baarish",
            urduScript: "بارش",
            english: "Rain",
            exampleSentence: "Baarish ho rahi hai.",
          },
          {
            id: 159,
            romanUrdu: "Mausam",
            urduScript: "موسم",
            english: "Weather",
            exampleSentence: "Mausam acha hai.",
          },
        ],
      },
    ],
  },
];
