/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as UrduTreasuryRouteImport } from './routes/urdu-treasury'
import { Route as TodaysMissionRouteImport } from './routes/todays-mission'
import { Route as ReviveUrduRouteImport } from './routes/revive-urdu'
import { Route as MyProgressRouteImport } from './routes/my-progress'
import { Route as MyDictionaryRouteImport } from './routes/my-dictionary'
import { Route as Learn40DaysRouteImport } from './routes/learn-40-days'
import { Route as IdiomsStoriesRouteImport } from './routes/idioms-stories'
import { Route as IndexRouteImport } from './routes/index'

const UrduTreasuryRoute = UrduTreasuryRouteImport.update({
  id: '/urdu-treasury',
  path: '/urdu-treasury',
  getParentRoute: () => rootRouteImport,
} as any)
const TodaysMissionRoute = TodaysMissionRouteImport.update({
  id: '/todays-mission',
  path: '/todays-mission',
  getParentRoute: () => rootRouteImport,
} as any)
const ReviveUrduRoute = ReviveUrduRouteImport.update({
  id: '/revive-urdu',
  path: '/revive-urdu',
  getParentRoute: () => rootRouteImport,
} as any)
const MyProgressRoute = MyProgressRouteImport.update({
  id: '/my-progress',
  path: '/my-progress',
  getParentRoute: () => rootRouteImport,
} as any)
const MyDictionaryRoute = MyDictionaryRouteImport.update({
  id: '/my-dictionary',
  path: '/my-dictionary',
  getParentRoute: () => rootRouteImport,
} as any)
const Learn40DaysRoute = Learn40DaysRouteImport.update({
  id: '/learn-40-days',
  path: '/learn-40-days',
  getParentRoute: () => rootRouteImport,
} as any)
const IdiomsStoriesRoute = IdiomsStoriesRouteImport.update({
  id: '/idioms-stories',
  path: '/idioms-stories',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/idioms-stories': typeof IdiomsStoriesRoute
  '/learn-40-days': typeof Learn40DaysRoute
  '/my-dictionary': typeof MyDictionaryRoute
  '/my-progress': typeof MyProgressRoute
  '/revive-urdu': typeof ReviveUrduRoute
  '/todays-mission': typeof TodaysMissionRoute
  '/urdu-treasury': typeof UrduTreasuryRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/idioms-stories': typeof IdiomsStoriesRoute
  '/learn-40-days': typeof Learn40DaysRoute
  '/my-dictionary': typeof MyDictionaryRoute
  '/my-progress': typeof MyProgressRoute
  '/revive-urdu': typeof ReviveUrduRoute
  '/todays-mission': typeof TodaysMissionRoute
  '/urdu-treasury': typeof UrduTreasuryRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/idioms-stories': typeof IdiomsStoriesRoute
  '/learn-40-days': typeof Learn40DaysRoute
  '/my-dictionary': typeof MyDictionaryRoute
  '/my-progress': typeof MyProgressRoute
  '/revive-urdu': typeof ReviveUrduRoute
  '/todays-mission': typeof TodaysMissionRoute
  '/urdu-treasury': typeof UrduTreasuryRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/idioms-stories'
    | '/learn-40-days'
    | '/my-dictionary'
    | '/my-progress'
    | '/revive-urdu'
    | '/todays-mission'
    | '/urdu-treasury'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/idioms-stories'
    | '/learn-40-days'
    | '/my-dictionary'
    | '/my-progress'
    | '/revive-urdu'
    | '/todays-mission'
    | '/urdu-treasury'
  id:
    | '__root__'
    | '/'
    | '/idioms-stories'
    | '/learn-40-days'
    | '/my-dictionary'
    | '/my-progress'
    | '/revive-urdu'
    | '/todays-mission'
    | '/urdu-treasury'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  IdiomsStoriesRoute: typeof IdiomsStoriesRoute
  Learn40DaysRoute: typeof Learn40DaysRoute
  MyDictionaryRoute: typeof MyDictionaryRoute
  MyProgressRoute: typeof MyProgressRoute
  ReviveUrduRoute: typeof ReviveUrduRoute
  TodaysMissionRoute: typeof TodaysMissionRoute
  UrduTreasuryRoute: typeof UrduTreasuryRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/urdu-treasury': {
      id: '/urdu-treasury'
      path: '/urdu-treasury'
      fullPath: '/urdu-treasury'
      preLoaderRoute: typeof UrduTreasuryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/todays-mission': {
      id: '/todays-mission'
      path: '/todays-mission'
      fullPath: '/todays-mission'
      preLoaderRoute: typeof TodaysMissionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/revive-urdu': {
      id: '/revive-urdu'
      path: '/revive-urdu'
      fullPath: '/revive-urdu'
      preLoaderRoute: typeof ReviveUrduRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/my-progress': {
      id: '/my-progress'
      path: '/my-progress'
      fullPath: '/my-progress'
      preLoaderRoute: typeof MyProgressRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/my-dictionary': {
      id: '/my-dictionary'
      path: '/my-dictionary'
      fullPath: '/my-dictionary'
      preLoaderRoute: typeof MyDictionaryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/learn-40-days': {
      id: '/learn-40-days'
      path: '/learn-40-days'
      fullPath: '/learn-40-days'
      preLoaderRoute: typeof Learn40DaysRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/idioms-stories': {
      id: '/idioms-stories'
      path: '/idioms-stories'
      fullPath: '/idioms-stories'
      preLoaderRoute: typeof IdiomsStoriesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  IdiomsStoriesRoute: IdiomsStoriesRoute,
  Learn40DaysRoute: Learn40DaysRoute,
  MyDictionaryRoute: MyDictionaryRoute,
  MyProgressRoute: MyProgressRoute,
  ReviveUrduRoute: ReviveUrduRoute,
  TodaysMissionRoute: TodaysMissionRoute,
  UrduTreasuryRoute: UrduTreasuryRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
